based on: https://www.youtube.com/watch?v=fhiUl7f5DnI

# Cars Dataset
In this project data of different cars is given with their specifications. The data is in CVS format, and it is analyzed using Pandas DataFrame

In [8]:
import pandas as pd
pd.set_option('display.expand_frame_repr', False) # for showing width of the colums better

In [72]:
cars = pd.read_csv('cars_dataset.csv')

In [27]:
cars.head(10)

    Make                    Model    Type  Origin DriveTrain      MSRP   Invoice  EngineSize  Cylinders  Horsepower  MPG_City  MPG_Highway  Weight  Wheelbase  Length
0  Acura                      MDX     SUV    Asia        All  $36,945   $33,337          3.5        6.0       265.0      17.0         23.0  4451.0      106.0   189.0
1  Acura           RSX Type S 2dr   Sedan    Asia      Front  $23,820   $21,761          2.0        4.0       200.0      24.0         31.0  2778.0      101.0   172.0
2  Acura                  TSX 4dr   Sedan    Asia      Front  $26,990   $24,647          2.4        4.0       200.0      22.0         29.0  3230.0      105.0   183.0
3  Acura                   TL 4dr   Sedan    Asia      Front  $33,195   $30,299          3.2        6.0       270.0      20.0         28.0  3575.0      108.0   186.0
4  Acura               3.5 RL 4dr   Sedan    Asia      Front  $43,755   $39,014          3.5        6.0       225.0      18.0         24.0  3880.0      115.0   197.0
5  Acura  3.5 RL w/Navigation 4dr   Sedan    Asia      Front  $46,100   $41,100          3.5        6.0       225.0      18.0         24.0  3893.0      115.0   197.0
6  Acura   NSX coupe 2dr manual S  Sports    Asia       Rear  $89,765   $79,978          3.2        6.0       290.0      17.0         24.0  3153.0      100.0   174.0
7   Audi              A4 1.8T 4dr   Sedan  Europe      Front  $25,940   $23,508          1.8        4.0       170.0      22.0         31.0  3252.0      104.0   179.0
8   Audi   A41.8T convertible 2dr   Sedan  Europe      Front  $35,940   $32,506          1.8        4.0       170.0      23.0         30.0  3638.0      105.0   180.0
9   Audi               A4 3.0 4dr   Sedan  Europe      Front  $31,840   $28,846          3.0        6.0       220.0      20.0         28.0  3462.0      104.0   179.0

### **Q1) Find all Null Value in the dataset. If there is any null value in any column, then fill it with the mean of that column.**

In [43]:
# how many nulls are in each column
cars.isnull().sum()
# Check if there are records where all values are NaN
cars[cars.isnull().any(axis=1)]
# 4 rows have only NaN values this rows would be removed from dataframe
cars = cars.dropna(how='all')
cars[cars.isnull().any(axis=1)]
# now only two rows cointain NaN values for Cylinder column
cars["Cylinders"].fillna(cars["Cylinders"].mean(), inplace=True)

# Check for NaN values again 
cars.isnull().sum()

Make           0
Model          0
Type           0
Origin         0
DriveTrain     0
MSRP           0
Invoice        0
EngineSize     0
Cylinders      0
Horsepower     0
MPG_City       0
MPG_Highway    0
Weight         0
Wheelbase      0
Length         0
dtype: int64

### **Q2) Check what are the different types of Make are there in dataset and what is the count (occurence) of each Make in the data.**

In [45]:
cars["Make"].value_counts()
# cars["Make"].unique()

array(['Acura', 'Audi', 'BMW', 'Buick', 'Cadillac', 'Chevrolet',
       'Chrysler', 'Dodge', 'Ford', 'GMC', 'Honda', 'Hummer', 'Hyundai',
       'Infiniti', 'Isuzu', 'Jaguar', 'Jeep', 'Kia', 'Land Rover',
       'Lexus', 'Lincoln', 'MINI', 'Mazda', 'Mercedes-Benz', 'Mercury',
       'Mitsubishi', 'Nissan', 'Oldsmobile', 'Pontiac', 'Porsche', 'Saab',
       'Saturn', 'Scion', 'Subaru', 'Suzuki', 'Toyota', 'Volkswagen',
       'Volvo'], dtype=object)

### **Q3) Show all records where Origin is Asia or Europe.**

In [51]:
cars.columns
sol1 = cars[(cars["Origin"]=="Asia") | (cars["Origin"]=="Europe")]
sol2 = cars[cars["Origin"].isin(["Asia","Europe"])]

print(f'There are {len(sol1)} cars using solution 1 and {len(sol2)} using solution 2')

There are 281 cars using solution 1 and 281 using solution 2

### **Q4) Remove all the records (rows) where Weight is above 4000.**

In [55]:
cars[~(cars["Weight"] > 4000)]

      Make                    Model   Type  Origin DriveTrain      MSRP   Invoice  EngineSize  Cylinders  Horsepower  MPG_City  MPG_Highway  Weight  Wheelbase  Length
1    Acura           RSX Type S 2dr  Sedan    Asia      Front  $23,820   $21,761          2.0        4.0       200.0      24.0         31.0  2778.0      101.0   172.0
2    Acura                  TSX 4dr  Sedan    Asia      Front  $26,990   $24,647          2.4        4.0       200.0      22.0         29.0  3230.0      105.0   183.0
3    Acura                   TL 4dr  Sedan    Asia      Front  $33,195   $30,299          3.2        6.0       270.0      20.0         28.0  3575.0      108.0   186.0
4    Acura               3.5 RL 4dr  Sedan    Asia      Front  $43,755   $39,014          3.5        6.0       225.0      18.0         24.0  3880.0      115.0   197.0
5    Acura  3.5 RL w/Navigation 4dr  Sedan    Asia      Front  $46,100   $41,100          3.5        6.0       225.0      18.0         24.0  3893.0      115.0   197.0
..     ...                      ...    ...     ...        ...       ...       ...         ...        ...         ...       ...          ...     ...        ...     ...
427  Volvo  C70 LPT convertible 2dr  Sedan  Europe      Front  $40,565   $38,203          2.4        5.0       197.0      21.0         28.0  3450.0      105.0   186.0
428  Volvo  C70 HPT convertible 2dr  Sedan  Europe      Front  $42,565   $40,083          2.3        5.0       242.0      20.0         26.0  3450.0      105.0   186.0
429  Volvo               S80 T6 4dr  Sedan  Europe      Front  $45,210   $42,573          2.9        6.0       268.0      19.0         26.0  3653.0      110.0   190.0
430  Volvo                      V40  Wagon  Europe      Front  $26,135   $24,641          1.9        4.0       170.0      22.0         29.0  2822.0      101.0   180.0
431  Volvo                     XC70  Wagon  Europe        All  $35,145   $33,112          2.5        5.0       208.0      20.0         27.0  3823.0      109.0   186.0

[325 rows x 15 columns]

### **Q5) Increase all the values of "MPG_City" column by 3.**

In [73]:
cars["MPG_City"] = cars["MPG_City"].apply(lambda x:x+3)
cars

      Make                    Model   Type  Origin DriveTrain      MSRP   Invoice  EngineSize  Cylinders  Horsepower  MPG_City  MPG_Highway  Weight  Wheelbase  Length
0    Acura                      MDX    SUV    Asia        All  $36,945   $33,337          3.5        6.0       265.0      20.0         23.0  4451.0      106.0   189.0
1    Acura           RSX Type S 2dr  Sedan    Asia      Front  $23,820   $21,761          2.0        4.0       200.0      27.0         31.0  2778.0      101.0   172.0
2    Acura                  TSX 4dr  Sedan    Asia      Front  $26,990   $24,647          2.4        4.0       200.0      25.0         29.0  3230.0      105.0   183.0
3    Acura                   TL 4dr  Sedan    Asia      Front  $33,195   $30,299          3.2        6.0       270.0      23.0         28.0  3575.0      108.0   186.0
4    Acura               3.5 RL 4dr  Sedan    Asia      Front  $43,755   $39,014          3.5        6.0       225.0      21.0         24.0  3880.0      115.0   197.0
..     ...                      ...    ...     ...        ...       ...       ...         ...        ...         ...       ...          ...     ...        ...     ...
427  Volvo  C70 LPT convertible 2dr  Sedan  Europe      Front  $40,565   $38,203          2.4        5.0       197.0      24.0         28.0  3450.0      105.0   186.0
428  Volvo  C70 HPT convertible 2dr  Sedan  Europe      Front  $42,565   $40,083          2.3        5.0       242.0      23.0         26.0  3450.0      105.0   186.0
429  Volvo               S80 T6 4dr  Sedan  Europe      Front  $45,210   $42,573          2.9        6.0       268.0      22.0         26.0  3653.0      110.0   190.0
430  Volvo                      V40  Wagon  Europe      Front  $26,135   $24,641          1.9        4.0       170.0      25.0         29.0  2822.0      101.0   180.0
431  Volvo                     XC70  Wagon  Europe        All  $35,145   $33,112          2.5        5.0       208.0      23.0         27.0  3823.0      109.0   186.0

[432 rows x 15 columns]